### ISSUE TITLE
Question regarding parameters used in this example

### ISSUE THREAD

**Issue by deepanshu761999** [Accelergy-Project/processing-in-memory-design#2]
is this relates(same parameters) to ADC-based architecture presented in ISAAC. And used in PIM accelerator energy estimation example in "An Architecture-Level Energy and Area Estimator for Processing-In-Memory Accelerator Designs"

**Comment by nellie-wu** [comment]
This is a simpler version of the ADC-based architecture presented in ISAAC but can serve as an approximate.
