### ISSUE TITLE
Seeing the following error when I run the experiment from PIM

### ISSUE THREAD

**Issue by crsumiran** [Accelergy-Project/processing-in-memory-design#3]
timeloop-mapper: src/model/topology.cpp:198: void model::Topology::Specs::ParseAccelergyERT(config::CompoundConfigNode): Assertion `false' failed.

**Comment by nellie-wu** [comment]
Thanks for letting us know -- this error is due to a recent update on timeloop code. We will work on the fix. In the meantime, you can check out the V2.0 release commit: https://github.com/NVlabs/timeloop/releases/tag/v2.0, which does not have the problem.

**Comment by crsumiran** [comment]
Thank you so much nellie-wu. It worked with the latest version :)
