### ISSUE TITLE
Error when running Timeloop Mapper

### ISSUE THREAD

**Issue by JueonPark** [Accelergy-Project/processing-in-memory-design#4]
I ran the following command in README.md
``` bash
timeloop-mapper arch/system_PIM.yaml arch/components/*.yaml mapper/mapper.yaml constraints/*.yaml example_layer.yaml
```
Then, the following error message occurred.

``` text
================================================================================
                                TIMELOOP MAPPER
================================================================================
TID      Total    Invalid      Valid    Consec.       Last   Opt.util Opt.energy
                                        invalid     update
--------------------------------------------------------------------------------
  0         16         16          0         16          0
  1         16         16          0         16          0
  2         16         16          0         16          0
  3         16         16          0         16          0
  4         19         19          0         19          0timeloop-mapper: src/compound-config/compound-config.cpp:522: bool config::CompoundConfigNode::getMapKeys(std::vector<std::__cxx11::basic_string<char> >&): Assertion `YNode.IsMap()' failed.   2          0
  7          2          2          0       Aborted (core dumped)
```

There was no code modification and I reinstalled timeloop inside the docker since the docker's timeloop version was not 2.0 (#3 ).

Thanks,
Jueon Park

**Comment by nellie-wu** [comment]
The current latest timeloop master already has the issue fixed, so please feel free to use the most-up-to-date code.

Would you please provide some information on how was timeloop reinstalled inside the docker? Was the built executable moved to `/usr/local/bin`?

It would be great if you are able to install the timeloop natively to test if it still has the same problem. Option 2 here: https://accelergy.mit.edu/infra_instructions.html

**Comment by JueonPark** [comment]
The built executable is inside the timeloop directory's `bin`. I'll try for the latest version and native install.
