### ISSUE TITLE
wrong  num_destination for D2A_NoC

### ISSUE THREAD

**Issue by deepanshu761999** [Accelergy-Project/processing-in-memory-design#5]
In line number 29, I think it should be "action_share: num_destinations". Also, it appears that D2A_NoC is between shared_glb and dummy buffer. But then, wouldn't the "num_destinations" be 1 always? so, D2A_converter's convert action is invoked only once per input? @nellie-wu 

![Screenshot from 2022-04-06 04-27-27](https://user-images.githubusercontent.com/52217613/161864872-ed16d488-5517-468e-a300-49f44646484f.png)
also, action_share of DAC_SimpleMulticast seems to have no effect on energy( check ERT yaml )
![Screenshot from 2022-04-13 04-06-04](https://user-images.githubusercontent.com/52217613/163070708-34e108be-232c-43a9-911c-bdde30d08e61.png)

**Comment by nellie-wu** [comment]
Thanks for pointing out the problems! We are looking into it and will get back with new updates.
